version: "3"
services:
  golang:
    build: ./golang
    ports:
      - "8088:8088"
    links:
      - "mysql"
      - "redis"
    volumes:
      - $HOME/code/go:/go
    tty: true
  mysql:
    image: mysql:5.7
    ports:
      - "3306:33066"
    volumes:
      - /home/code/data/golang-mysql/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  redis:
    image: redis
    ports:
      - "6379:63791"　　